%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Amanda\Desktop\FaceSpace\2kattributes\Full
%    Attribute Scores\psychology attributes\psychology-attributes.xlsx
%    Worksheet: Final Values
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2015/05/30 14:19:52

%% Import the data
clear all; clc; 
[~, ~, raw] = xlsread('C:\Users\Amanda\Desktop\FaceSpace\2kattributes\Full Attribute Scores\psychology attributes\psychology-attributes.xlsx','Final Values','B2:AZ2223');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Image = data(:,1);
atypical = data(:,2);
boring = data(:,3);
calm = data(:,4);
catch1 = data(:,5);
catchAns = data(:,6);
cold = data(:,7);
common = data(:,8);
confident = data(:,9);
egotistic = data(:,10);
emotUnstable = data(:,11);
forgettable = data(:,12);
intelligent = data(:,13);
introverted = data(:,14);
kind = data(:,15);
responsible = data(:,16);
subage = data(:,17);
submale = data(:,18);
subrace = data(:,19);
trustworthy = data(:,20);
unattractive = data(:,21);
unemotional = data(:,22);
unfamiliar = data(:,23);
unfriendly = data(:,24);
unhappy = data(:,25);
weird = data(:,26);
aggressive = data(:,27);
attractive = data(:,28);
caring = data(:,29);
catch2 = data(:,30);
catchAns1 = data(:,31);
emotStable = data(:,32);
emotional = data(:,33);
familiar = data(:,34);
friendly = data(:,35);
happy = data(:,36);
humble = data(:,37);
interesting = data(:,38);
irresponsible = data(:,39);
mean1 = data(:,40);
memorable = data(:,41);
normal = data(:,42);
sociable = data(:,43);
subage1 = data(:,44);
submale1 = data(:,45);
subrace1 = data(:,46);
typical = data(:,47);
uncertain = data(:,48);
uncommon = data(:,49);
unintelligent = data(:,50);
untrustworthy = data(:,51);

% keepList

socialFeatureList = zeros(size(data,1),24);
socialFeatureList(:,1) = data(:,2);% atypical
socialFeatureList(:,2) = data(:,3);% boring
socialFeatureList(:,3) = data(:,4);% calm
socialFeatureList(:,4) = data(:,7);% cold
socialFeatureList(:,5) = data(:,8);% common
socialFeatureList(:,6) = data(:,9);% confident
socialFeatureList(:,7) = data(:,10);% egotistic
socialFeatureList(:,8) = data(:,33);% emotional
socialFeatureList(:,9) = data(:,12);% forgetable
socialFeatureList(:,10) = data(:,13);% intelligent
socialFeatureList(:,11) = data(:,14);% introverted
socialFeatureList(:,12) = data(:,15);% kind
socialFeatureList(:,13) = data(:,16);% responsible
socialFeatureList(:,14) = data(:,20);% trustworthy
socialFeatureList(:,15) = data(:,27);% agressive
socialFeatureList(:,16) = data(:,28);% attractive
socialFeatureList(:,17) = data(:,29);% caring
socialFeatureList(:,18) = data(:,34);% familiar
socialFeatureList(:,19) = data(:,35);% friendly
socialFeatureList(:,20) = data(:,36);% happy
socialFeatureList(:,21) = data(:,37);% humble
socialFeatureList(:,22) = data(:,38);% intersting
socialFeatureList(:,23) = data(:,41);% memorable
socialFeatureList(:,24) = data(:,43);% sociable

save('socialFeatureList.mat','socialFeatureList');



